<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Pantallas\DocenteVentanas\FrmPlanificacionActividadesMalo.cs" />
    <Compile Remove="Pantallas\DocenteVentanas\FrmPlanificacionActividadesMalo.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Pantallas\DocenteVentanas\FrmPlanificacionActividadesMalo.resx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Guna.UI2.WinForms" Version="2.0.4.7" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.5.0" />
    <PackageReference Include="itext7" Version="9.5.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="WinForms.DataVisualization" Version="1.10.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Pantallas\DocenteVentanas\FrmReporteSemanal.cs" />
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

	<ItemGroup>
		<Compile Update="Pantallas\AdminVentanas\FrmNuevaReunion.cs">
			<SubType>Form</SubType>
		</Compile>

		<Compile Update="Pantallas\AdminVentanas\FrmNuevaReunion.Designer.cs">
			<DependentUpon>FrmNuevaReunion.cs</DependentUpon>
		</Compile>

		<EmbeddedResource Update="Pantallas\AdminVentanas\FrmNuevaReunion.resx">
			<DependentUpon>FrmNuevaReunion.cs</DependentUpon>
			<SubType>Designer</SubType>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Pantallas\DocenteVentanas\FrmReporteAsistencia.cs">
			<SubType>Form</SubType>
		</Compile>

		<Compile Update="Pantallas\DocenteVentanas\FrmReporteAsistencia.Designer.cs">
			<DependentUpon>FrmReporteAsistencia.cs</DependentUpon>
		</Compile>

		<EmbeddedResource Update="Pantallas\DocenteVentanas\FrmReporteAsistencia.resx">
			<DependentUpon>FrmReporteAsistencia.cs</DependentUpon>
			<SubType>Designer</SubType>
		</EmbeddedResource>

		<EmbeddedResource Update="Properties\Resources.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>